import type { ListeningVideo } from './types';

export const listeningData: ListeningVideo[] = [
  // ── Daily Conversation ─────────────────────────────────────────────────────
  {
    id: 'lv1',
    youtubeId: 'DYzT-Pk6Ogk',
    title: 'English Conversation Practice – Daily Routines',
    channel: 'BBC Learning English',
    duration: '3:24',
    cefrLevel: 'A2',
    category: 'Daily Conversation',
    thumbnailUrl: 'https://img.youtube.com/vi/DYzT-Pk6Ogk/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 5, text: 'Good morning! What time do you usually wake up?', translation_id: 'Selamat pagi! Pukul berapa kamu biasanya bangun?' },
      { id: 's2', startTime: 5, endTime: 11, text: 'I usually wake up at seven o\'clock every day.', translation_id: 'Saya biasanya bangun pukul tujuh setiap hari.' },
      { id: 's3', startTime: 11, endTime: 18, text: 'Do you have breakfast before going to work?', translation_id: 'Apakah kamu sarapan sebelum pergi bekerja?' },
      { id: 's4', startTime: 18, endTime: 25, text: 'Yes, I always eat breakfast. It is very important.', translation_id: 'Ya, saya selalu sarapan. Itu sangat penting.' },
      { id: 's5', startTime: 25, endTime: 33, text: 'How do you get to work? Do you take the bus?', translation_id: 'Bagaimana kamu pergi ke tempat kerja? Apakah kamu naik bus?' },
      { id: 's6', startTime: 33, endTime: 40, text: 'No, I usually drive. The bus takes too long.', translation_id: 'Tidak, saya biasanya berkendara. Bus terlalu lama.' },
      { id: 's7', startTime: 40, endTime: 48, text: 'What do you do in the evenings after work?', translation_id: 'Apa yang kamu lakukan di malam hari setelah bekerja?' },
      { id: 's8', startTime: 48, endTime: 56, text: 'I like to cook dinner and watch television.', translation_id: 'Saya suka memasak makan malam dan menonton televisi.' },
    ],
  },
  {
    id: 'lv2',
    youtubeId: 'GbQgDMsGb4w',
    title: 'At the Coffee Shop – English Dialogue',
    channel: 'VOA Learning English',
    duration: '2:58',
    cefrLevel: 'A1',
    category: 'Daily Conversation',
    thumbnailUrl: 'https://img.youtube.com/vi/GbQgDMsGb4w/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 5, text: 'Hello! What can I get for you today?', translation_id: 'Halo! Apa yang bisa saya bantu untuk Anda hari ini?' },
      { id: 's2', startTime: 5, endTime: 11, text: 'I would like a large coffee, please.', translation_id: 'Saya ingin kopi ukuran besar, tolong.' },
      { id: 's3', startTime: 11, endTime: 18, text: 'Would you like milk or sugar in your coffee?', translation_id: 'Apakah Anda ingin susu atau gula dalam kopi Anda?' },
      { id: 's4', startTime: 18, endTime: 25, text: 'Just a little milk, thank you.', translation_id: 'Hanya sedikit susu, terima kasih.' },
      { id: 's5', startTime: 25, endTime: 33, text: 'That will be three dollars and fifty cents.', translation_id: 'Itu akan seharga tiga dolar lima puluh sen.' },
      { id: 's6', startTime: 33, endTime: 40, text: 'Here you go. Keep the change.', translation_id: 'Ini dia. Ambil kembaliannya.' },
      { id: 's7', startTime: 40, endTime: 47, text: 'Thank you very much. Have a nice day!', translation_id: 'Terima kasih banyak. Semoga hari Anda menyenangkan!' },
    ],
  },

  // ── BBC/VOA ─────────────────────────────────────────────────────────────────
  {
    id: 'lv3',
    youtubeId: 'AUiDxuYnGAE',
    title: 'BBC 6 Minute English – Artificial Intelligence',
    channel: 'BBC Learning English',
    duration: '6:01',
    cefrLevel: 'B2',
    category: 'BBC/VOA',
    thumbnailUrl: 'https://img.youtube.com/vi/AUiDxuYnGAE/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 7, text: 'Hello, and welcome to Six Minute English from the BBC.', translation_id: 'Halo, dan selamat datang di Bahasa Inggris Enam Menit dari BBC.' },
      { id: 's2', startTime: 7, endTime: 15, text: 'Today we are talking about artificial intelligence and how it affects our lives.', translation_id: 'Hari ini kita berbicara tentang kecerdasan buatan dan bagaimana hal itu mempengaruhi kehidupan kita.' },
      { id: 's3', startTime: 15, endTime: 24, text: 'AI systems can now write articles, create images, and even compose music.', translation_id: 'Sistem AI sekarang dapat menulis artikel, membuat gambar, bahkan menggubah musik.' },
      { id: 's4', startTime: 24, endTime: 33, text: 'Many people are concerned about what this means for human workers.', translation_id: 'Banyak orang khawatir tentang apa artinya ini bagi pekerja manusia.' },
      { id: 's5', startTime: 33, endTime: 42, text: 'However, some experts believe AI will create more jobs than it replaces.', translation_id: 'Namun, beberapa ahli percaya AI akan menciptakan lebih banyak pekerjaan daripada yang digantikannya.' },
      { id: 's6', startTime: 42, endTime: 51, text: 'The key question is whether humans and machines can work together effectively.', translation_id: 'Pertanyaan kuncinya adalah apakah manusia dan mesin dapat bekerja sama secara efektif.' },
      { id: 's7', startTime: 51, endTime: 60, text: 'Learning to use these tools will become an essential skill.', translation_id: 'Mempelajari cara menggunakan alat-alat ini akan menjadi keterampilan yang sangat penting.' },
    ],
  },
  {
    id: 'lv4',
    youtubeId: 'sF4HQ5oDqzA',
    title: 'VOA News – Climate Change Effects',
    channel: 'VOA Learning English',
    duration: '4:15',
    cefrLevel: 'B1',
    category: 'BBC/VOA',
    thumbnailUrl: 'https://img.youtube.com/vi/sF4HQ5oDqzA/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 6, text: 'Scientists say climate change is happening faster than expected.', translation_id: 'Para ilmuwan mengatakan perubahan iklim terjadi lebih cepat dari yang diperkirakan.' },
      { id: 's2', startTime: 6, endTime: 14, text: 'Global temperatures have risen by more than one degree Celsius.', translation_id: 'Suhu global telah naik lebih dari satu derajat Celsius.' },
      { id: 's3', startTime: 14, endTime: 22, text: 'This is causing more extreme weather events around the world.', translation_id: 'Hal ini menyebabkan lebih banyak peristiwa cuaca ekstrem di seluruh dunia.' },
      { id: 's4', startTime: 22, endTime: 30, text: 'Sea levels are rising, threatening coastal communities.', translation_id: 'Permukaan laut naik, mengancam komunitas pesisir.' },
      { id: 's5', startTime: 30, endTime: 39, text: 'Governments are under pressure to reduce carbon emissions quickly.', translation_id: 'Pemerintah berada di bawah tekanan untuk mengurangi emisi karbon dengan cepat.' },
      { id: 's6', startTime: 39, endTime: 47, text: 'Renewable energy sources like solar and wind power are growing rapidly.', translation_id: 'Sumber energi terbarukan seperti tenaga surya dan angin berkembang pesat.' },
    ],
  },

  // ── Songs ───────────────────────────────────────────────────────────────────
  {
    id: 'lv5',
    youtubeId: 'CevxZvSJLk8',
    title: 'Adele – Someone Like You (Lyrics)',
    channel: 'Adele Official',
    duration: '4:45',
    cefrLevel: 'B1',
    category: 'Songs',
    thumbnailUrl: 'https://img.youtube.com/vi/CevxZvSJLk8/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 8, text: 'I heard that you are settled down.', translation_id: 'Aku dengar kamu sudah menetap.' },
      { id: 's2', startTime: 8, endTime: 16, text: 'That you found a girl and you are married now.', translation_id: 'Bahwa kamu menemukan seorang gadis dan sekarang sudah menikah.' },
      { id: 's3', startTime: 16, endTime: 24, text: 'I heard that your dreams came true.', translation_id: 'Aku dengar impianmu menjadi kenyataan.' },
      { id: 's4', startTime: 24, endTime: 32, text: 'Guess she gave you things I did not give to you.', translation_id: 'Kurasa dia memberimu hal-hal yang tidak aku berikan kepadamu.' },
      { id: 's5', startTime: 32, endTime: 42, text: 'Never mind, I will find someone like you.', translation_id: 'Tidak apa-apa, aku akan menemukan seseorang sepertimu.' },
      { id: 's6', startTime: 42, endTime: 52, text: 'I wish nothing but the best for you, too.', translation_id: 'Aku hanya berharap yang terbaik untukmu juga.' },
    ],
  },
  {
    id: 'lv6',
    youtubeId: 'kffacxfA7G4',
    title: 'Ed Sheeran – Perfect (Lyrics)',
    channel: 'Ed Sheeran Official',
    duration: '4:23',
    cefrLevel: 'A2',
    category: 'Songs',
    thumbnailUrl: 'https://img.youtube.com/vi/kffacxfA7G4/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 8, text: 'I found a love for me.', translation_id: 'Aku menemukan cinta untuk diriku.' },
      { id: 's2', startTime: 8, endTime: 16, text: 'Darling just dive right in and follow my lead.', translation_id: 'Sayang, langsung terjun dan ikuti arahku.' },
      { id: 's3', startTime: 16, endTime: 25, text: 'Well I found a girl, beautiful and sweet.', translation_id: 'Baik, aku menemukan gadis yang cantik dan manis.' },
      { id: 's4', startTime: 25, endTime: 34, text: 'I never knew you were the someone waiting for me.', translation_id: 'Aku tidak pernah tahu bahwa kamu adalah seseorang yang menungguku.' },
      { id: 's5', startTime: 34, endTime: 43, text: 'Baby I am dancing in the dark with you between my arms.', translation_id: 'Sayang, aku menari dalam gelap denganmu di antara lenganku.' },
    ],
  },

  // ── TOEIC/IELTS ─────────────────────────────────────────────────────────────
  {
    id: 'lv7',
    youtubeId: 'IFDYdqpkTM4',
    title: 'IELTS Listening Practice – Academic Test',
    channel: 'IELTS Official',
    duration: '5:30',
    cefrLevel: 'C1',
    category: 'TOEIC/IELTS',
    thumbnailUrl: 'https://img.youtube.com/vi/IFDYdqpkTM4/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 7, text: 'Good afternoon and welcome to the university orientation session.', translation_id: 'Selamat siang dan selamat datang di sesi orientasi universitas.' },
      { id: 's2', startTime: 7, endTime: 16, text: 'My name is Professor Williams and I will be your academic advisor.', translation_id: 'Nama saya Profesor Williams dan saya akan menjadi penasihat akademik Anda.' },
      { id: 's3', startTime: 16, endTime: 25, text: 'This semester you will need to complete four core modules.', translation_id: 'Semester ini Anda perlu menyelesaikan empat modul inti.' },
      { id: 's4', startTime: 25, endTime: 35, text: 'Each module requires a minimum of eighty percent attendance.', translation_id: 'Setiap modul memerlukan kehadiran minimal delapan puluh persen.' },
      { id: 's5', startTime: 35, endTime: 45, text: 'Assignments must be submitted via the online portal by midnight.', translation_id: 'Tugas harus diserahkan melalui portal online sebelum tengah malam.' },
      { id: 's6', startTime: 45, endTime: 54, text: 'Please ensure you read the academic integrity policy carefully.', translation_id: 'Pastikan Anda membaca kebijakan integritas akademik dengan seksama.' },
    ],
  },
  {
    id: 'lv8',
    youtubeId: 'Gu_v_ZEfFhQ',
    title: 'TOEIC Listening – Business Meeting',
    channel: 'TOEIC Preparation',
    duration: '4:00',
    cefrLevel: 'B2',
    category: 'TOEIC/IELTS',
    thumbnailUrl: 'https://img.youtube.com/vi/Gu_v_ZEfFhQ/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 7, text: 'Let us begin our quarterly review meeting.', translation_id: 'Mari kita mulai rapat tinjauan kuartalan kita.' },
      { id: 's2', startTime: 7, endTime: 14, text: 'Sales figures for this quarter exceeded our projections.', translation_id: 'Angka penjualan untuk kuartal ini melebihi proyeksi kita.' },
      { id: 's3', startTime: 14, endTime: 22, text: 'The marketing campaign brought in thirty percent more leads.', translation_id: 'Kampanye pemasaran mendatangkan tiga puluh persen lebih banyak prospek.' },
      { id: 's4', startTime: 22, endTime: 31, text: 'However, production costs have increased due to supply chain issues.', translation_id: 'Namun, biaya produksi meningkat karena masalah rantai pasokan.' },
      { id: 's5', startTime: 31, endTime: 40, text: 'We need to find ways to reduce our operational expenses.', translation_id: 'Kita perlu menemukan cara untuk mengurangi pengeluaran operasional kita.' },
      { id: 's6', startTime: 40, endTime: 49, text: 'Are there any questions before we move to the next agenda item?', translation_id: 'Apakah ada pertanyaan sebelum kita pindah ke item agenda berikutnya?' },
    ],
  },

  // ── Movie Clips ─────────────────────────────────────────────────────────────
  {
    id: 'lv9',
    youtubeId: 'apzXGEbZht0',
    title: 'The Lion King – Iconic Movie Dialogue',
    channel: 'Disney Clips',
    duration: '3:10',
    cefrLevel: 'B1',
    category: 'Movie Clips',
    thumbnailUrl: 'https://img.youtube.com/vi/apzXGEbZht0/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 7, text: 'Oh yes, the past can hurt.', translation_id: 'Oh ya, masa lalu bisa menyakitkan.' },
      { id: 's2', startTime: 7, endTime: 16, text: 'But the way I see it, you can either run from it, or learn from it.', translation_id: 'Tapi menurut cara pandang saya, kamu bisa melarikan diri darinya, atau belajar darinya.' },
      { id: 's3', startTime: 16, endTime: 24, text: 'The question is, who are you?', translation_id: 'Pertanyaannya adalah, siapa kamu?' },
      { id: 's4', startTime: 24, endTime: 32, text: 'You are more than what you have become.', translation_id: 'Kamu lebih dari apa yang telah kamu jadikan.' },
      { id: 's5', startTime: 32, endTime: 40, text: 'Remember who you are.', translation_id: 'Ingatlah siapa dirimu.' },
    ],
  },
  {
    id: 'lv10',
    youtubeId: 'J0lSMBUBkYU',
    title: 'Forrest Gump – Life is Like a Box of Chocolates',
    channel: 'Paramount Clips',
    duration: '2:45',
    cefrLevel: 'B1',
    category: 'Movie Clips',
    thumbnailUrl: 'https://img.youtube.com/vi/J0lSMBUBkYU/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 7, text: 'Mama always said life was like a box of chocolates.', translation_id: 'Mama selalu bilang hidup itu seperti kotak cokelat.' },
      { id: 's2', startTime: 7, endTime: 15, text: 'You never know what you are gonna get.', translation_id: 'Kamu tidak pernah tahu apa yang akan kamu dapatkan.' },
      { id: 's3', startTime: 15, endTime: 24, text: 'I do not know if we each have a destiny, or if we are all just floating around accidentally.', translation_id: 'Saya tidak tahu apakah kita masing-masing memiliki takdir, atau apakah kita semua hanya mengambang secara kebetulan.' },
      { id: 's4', startTime: 24, endTime: 33, text: 'But I think maybe it is both. Maybe both is happening at the same time.', translation_id: 'Tapi saya pikir mungkin keduanya. Mungkin keduanya terjadi pada saat yang sama.' },
    ],
  },

  // ── Kids ────────────────────────────────────────────────────────────────────
  {
    id: 'lv11',
    youtubeId: 'hIaOMvH6hpg',
    title: 'The Alphabet Song – Learn English for Kids',
    channel: 'Kids Learning Tube',
    duration: '2:00',
    cefrLevel: 'A1',
    category: 'Kids',
    thumbnailUrl: 'https://img.youtube.com/vi/hIaOMvH6hpg/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 5, text: 'A B C D E F G', translation_id: 'A B C D E F G' },
      { id: 's2', startTime: 5, endTime: 10, text: 'H I J K L M N O P', translation_id: 'H I J K L M N O P' },
      { id: 's3', startTime: 10, endTime: 15, text: 'Q R S, T U V', translation_id: 'Q R S, T U V' },
      { id: 's4', startTime: 15, endTime: 22, text: 'W X, Y and Z', translation_id: 'W X, Y dan Z' },
      { id: 's5', startTime: 22, endTime: 30, text: 'Now I know my ABCs. Next time will you sing with me?', translation_id: 'Sekarang saya tahu ABC saya. Lain kali maukah kamu bernyanyi bersamaku?' },
    ],
  },
  {
    id: 'lv12',
    youtubeId: '6l1-d7Fc5MQ',
    title: 'Colors and Animals – English for Kids',
    channel: 'Super Simple Songs',
    duration: '3:05',
    cefrLevel: 'A1',
    category: 'Kids',
    thumbnailUrl: 'https://img.youtube.com/vi/6l1-d7Fc5MQ/mqdefault.jpg',
    transcript: [
      { id: 's1', startTime: 0, endTime: 6, text: 'The elephant is grey. The elephant is big.', translation_id: 'Gajah berwarna abu-abu. Gajah itu besar.' },
      { id: 's2', startTime: 6, endTime: 13, text: 'The frog is green. The frog can jump.', translation_id: 'Katak berwarna hijau. Katak bisa melompat.' },
      { id: 's3', startTime: 13, endTime: 20, text: 'The lion is yellow. The lion is strong.', translation_id: 'Singa berwarna kuning. Singa itu kuat.' },
      { id: 's4', startTime: 20, endTime: 27, text: 'The flamingo is pink. The flamingo can fly.', translation_id: 'Flamingo berwarna merah muda. Flamingo bisa terbang.' },
      { id: 's5', startTime: 27, endTime: 35, text: 'What color is your favourite animal?', translation_id: 'Warna apa hewan favoritmu?' },
    ],
  },
];

export const listeningCategories = ['All', 'Daily Conversation', 'BBC/VOA', 'Songs', 'TOEIC/IELTS', 'Movie Clips', 'Kids'] as const;
export type ListeningCategory = typeof listeningCategories[number];
