export type PartOfSpeech = 'noun' | 'verb' | 'adjective' | 'adverb' | 'phrase';
export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export interface VocabWord {
  id: string;
  word: string;
  pos: PartOfSpeech;
  level: CEFRLevel;
  ipa_us: string;
  ipa_uk: string;
  definition_en: string;
  definition_id: string;
  example_en: string;
  example_id: string;
  category: string;
  emoji: string;
  contexts?: {
    tech: string;
    business: string;
    casual: string;
  };
}

export const vocabularyData: VocabWord[] = [
  // ── Business (5) ──────────────────────────────────────────────────────────
  { id: 'b1', word: 'negotiate', pos: 'verb', level: 'B2', ipa_us: '/nɪˈɡoʊʃieɪt/', ipa_uk: '/nɪˈɡəʊʃieɪt/', definition_en: 'To discuss something in order to reach an agreement', definition_id: 'Bernegosiasi untuk mencapai kesepakatan', example_en: 'We need to negotiate the contract terms before signing.', example_id: 'Kita perlu menegosiasikan syarat kontrak sebelum menandatangani.', category: 'Business', emoji: '🤝', contexts: { tech: 'Engineers negotiate API contracts to ensure backward compatibility.', business: 'Both parties agreed to negotiate the merger terms over three sessions.', casual: 'We had to negotiate with each other about which movie to watch tonight.' } },
  { id: 'b2', word: 'revenue', pos: 'noun', level: 'B1', ipa_us: '/ˈrevənuː/', ipa_uk: '/ˈrevənjuː/', definition_en: 'Income generated from business activities', definition_id: 'Pendapatan yang dihasilkan dari aktivitas bisnis', example_en: 'The company increased its revenue by 20% this quarter.', example_id: 'Perusahaan meningkatkan pendapatannya sebesar 20% kuartal ini.', category: 'Business', emoji: '💰', contexts: { tech: 'The SaaS platform generated its first recurring revenue after the product launch.', business: 'Diversifying revenue streams helps companies weather economic downturns.', casual: 'The small bakery finally started seeing real revenue after going viral on social media.' } },
  { id: 'b3', word: 'deadline', pos: 'noun', level: 'A2', ipa_us: '/ˈdedlaɪn/', ipa_uk: '/ˈdedlaɪn/', definition_en: 'The latest time by which something must be completed', definition_id: 'Batas waktu terakhir untuk menyelesaikan sesuatu', example_en: 'The project deadline is next Friday.', example_id: 'Batas waktu proyek adalah Jumat depan.', category: 'Business', emoji: '⏰', contexts: { tech: 'The team pushed hard to hit the sprint deadline before the client demo.', business: 'Missing the regulatory deadline could result in significant penalties.', casual: 'I have a deadline for my essay tomorrow so I cannot go out tonight.' } },
  { id: 'b4', word: 'leverage', pos: 'noun', level: 'C1', ipa_us: '/ˈlevərɪdʒ/', ipa_uk: '/ˈliːvərɪdʒ/', definition_en: 'Power or advantage used to achieve a goal', definition_id: 'Kekuatan atau keunggulan yang digunakan untuk mencapai tujuan', example_en: 'We can use our market position as leverage in negotiations.', example_id: 'Kita bisa menggunakan posisi pasar kita sebagai leverage dalam negosiasi.', category: 'Business', emoji: '⚖️', contexts: { tech: 'Developers leverage open-source frameworks to reduce build time significantly.', business: 'Our proprietary data gives us strong leverage over competitors in this market.', casual: 'Knowing the bus schedule gives you leverage when bargaining with the taxi driver.' } },
  { id: 'b5', word: 'streamline', pos: 'verb', level: 'B2', ipa_us: '/ˈstriːmlaɪn/', ipa_uk: '/ˈstriːmlaɪn/', definition_en: 'To make a process more efficient and effective', definition_id: 'Membuat proses lebih efisien dan efektif', example_en: 'We plan to streamline our operations to reduce costs.', example_id: 'Kita berencana menyederhanakan operasi untuk mengurangi biaya.', category: 'Business', emoji: '🔄', contexts: { tech: 'Automating tests helped streamline the deployment pipeline considerably.', business: 'The consultant was hired to streamline procurement and cut approval delays.', casual: 'She streamlined her morning routine so she could sleep an extra 20 minutes.' } },

  // ── Tech/AI (5) ───────────────────────────────────────────────────────────
  { id: 't1', word: 'algorithm', pos: 'noun', level: 'B2', ipa_us: '/ˈælɡərɪðəm/', ipa_uk: '/ˈælɡərɪðəm/', definition_en: 'A set of rules or instructions for solving a problem', definition_id: 'Sekumpulan aturan atau instruksi untuk memecahkan masalah', example_en: 'The search algorithm finds results in milliseconds.', example_id: 'Algoritma pencarian menemukan hasil dalam milidetik.', category: 'Tech/AI', emoji: '🔢', contexts: { tech: 'We optimised the sorting algorithm to reduce time complexity from O(n²) to O(n log n).', business: 'The recommendation algorithm increased average order value by 15 percent.', casual: 'Social media algorithms decide which posts you see first in your feed.' } },
  { id: 't2', word: 'deploy', pos: 'verb', level: 'B1', ipa_us: '/dɪˈplɔɪ/', ipa_uk: '/dɪˈplɔɪ/', definition_en: 'To put software into active service', definition_id: 'Menempatkan perangkat lunak ke layanan aktif', example_en: 'We will deploy the new version tonight.', example_id: 'Kita akan men-deploy versi baru malam ini.', category: 'Tech/AI', emoji: '🚀', contexts: { tech: 'We use GitHub Actions to deploy to production automatically on every merge to main.', business: 'The IT team will deploy the new ERP system during the maintenance window this weekend.', casual: 'The app developer deployed an update overnight and users woke up to a brand new look.' } },
  { id: 't3', word: 'bandwidth', pos: 'noun', level: 'B1', ipa_us: '/ˈbændwɪdθ/', ipa_uk: '/ˈbændwɪdθ/', definition_en: 'The amount of data transmitted over a network per second', definition_id: 'Jumlah data yang ditransmisikan melalui jaringan per detik', example_en: 'Video streaming requires high bandwidth.', example_id: 'Streaming video membutuhkan bandwidth tinggi.', category: 'Tech/AI', emoji: '📡', contexts: { tech: 'Our CDN architecture optimises bandwidth usage by caching assets at edge nodes.', business: "We don't have the bandwidth to take on another client this quarter.", casual: "I can't join the video call because my home internet bandwidth is too slow." } },
  { id: 't4', word: 'neural network', pos: 'phrase', level: 'C1', ipa_us: '/ˈnjʊrəl ˈnetwɜːrk/', ipa_uk: '/ˈnjʊərəl ˈnetwɜːk/', definition_en: 'A computing system inspired by the human brain that learns patterns', definition_id: 'Sistem komputasi yang terinspirasi otak manusia yang mempelajari pola', example_en: 'Neural networks power modern image recognition systems.', example_id: 'Jaringan saraf mentenagai sistem pengenalan gambar modern.', category: 'Tech/AI', emoji: '🧠', contexts: { tech: 'We trained a convolutional neural network on 100k labelled images to detect defects.', business: 'Investing in neural network research gave the startup a competitive moat in diagnostics.', casual: 'The app uses a neural network to guess your mood from your selfie.' } },
  { id: 't5', word: 'iterate', pos: 'verb', level: 'B2', ipa_us: '/ˈɪtəreɪt/', ipa_uk: '/ˈɪtəreɪt/', definition_en: 'To repeat a process in order to improve a result', definition_id: 'Mengulangi proses untuk meningkatkan hasil', example_en: 'We iterate quickly based on user feedback.', example_id: 'Kita beriterasi dengan cepat berdasarkan umpan balik pengguna.', category: 'Tech/AI', emoji: '🔁', contexts: { tech: 'Agile teams iterate in two-week sprints, releasing working software after each cycle.', business: 'We iterate our pricing strategy each quarter based on conversion data.', casual: 'I kept iterating on my recipe until the cookies finally turned out perfect.' } },

  // ── Daily Life (5) ────────────────────────────────────────────────────────
  { id: 'd1', word: 'routine', pos: 'noun', level: 'A2', ipa_us: '/ruːˈtiːn/', ipa_uk: '/ruːˈtiːn/', definition_en: 'A regular series of activities performed in a fixed order', definition_id: 'Serangkaian aktivitas rutin yang dilakukan dalam urutan tetap', example_en: 'Her morning routine starts with exercise.', example_id: 'Rutinitas paginya dimulai dengan olahraga.', category: 'Daily Life', emoji: '☀️', contexts: { tech: 'Setting up a code review routine helps maintain consistent quality across the team.', business: 'Our daily stand-up is part of the team routine that keeps everyone aligned.', casual: 'I have a bedtime routine that helps me fall asleep within minutes.' } },
  { id: 'd2', word: 'commute', pos: 'verb', level: 'B1', ipa_us: '/kəˈmjuːt/', ipa_uk: '/kəˈmjuːt/', definition_en: 'To travel regularly between home and work', definition_id: 'Perjalanan rutin antara rumah dan tempat kerja', example_en: 'He commutes by train every day.', example_id: 'Dia pergi ke kantor dengan kereta setiap hari.', category: 'Daily Life', emoji: '🚆', contexts: { tech: 'Many developers prefer remote work to avoid the daily commute and code in peace.', business: 'The company offers a commute subsidy to encourage employees to use public transport.', casual: 'My commute is only 10 minutes by bike, which is the best part of my day.' } },
  { id: 'd3', word: 'errand', pos: 'noun', level: 'A2', ipa_us: '/ˈerənd/', ipa_uk: '/ˈerənd/', definition_en: 'A short trip to do a specific task', definition_id: 'Perjalanan singkat untuk melakukan tugas tertentu', example_en: 'I need to run a few errands this afternoon.', example_id: 'Saya perlu menyelesaikan beberapa urusan sore ini.', category: 'Daily Life', emoji: '🛒', contexts: { tech: 'Delivery apps let robots run errands like grocery shopping with no human needed.', business: 'The assistant handled personal errands so the CEO could focus on strategic work.', casual: 'Can you run a quick errand for me and grab some milk from the corner store?' } },
  { id: 'd4', word: 'appliance', pos: 'noun', level: 'A2', ipa_us: '/əˈplaɪəns/', ipa_uk: '/əˈplaɪəns/', definition_en: 'An electrical device designed for home use', definition_id: 'Perangkat listrik yang dirancang untuk penggunaan rumah', example_en: 'The washing machine is my favourite appliance.', example_id: 'Mesin cuci adalah peralatan favorit saya.', category: 'Daily Life', emoji: '🏠', contexts: { tech: 'Smart appliances connect to Wi-Fi and can be controlled through a mobile app remotely.', business: 'The appliance manufacturer pivoted to IoT-enabled products to stay competitive.', casual: 'My favourite appliance is my air fryer because it makes everything crispy so fast.' } },
  { id: 'd5', word: 'clutter', pos: 'noun', level: 'B1', ipa_us: '/ˈklʌtər/', ipa_uk: '/ˈklʌtə/', definition_en: 'A collection of things lying about in an untidy state', definition_id: 'Kumpulan barang yang berserakan dalam keadaan berantakan', example_en: 'She cleared the clutter from her desk.', example_id: 'Dia membersihkan barang-barang berantakan dari mejanya.', category: 'Daily Life', emoji: '🗑️', contexts: { tech: 'Removing unused dependencies reduces clutter in the codebase and speeds up builds.', business: 'The manager asked the team to clear inbox clutter by using a proper project tool.', casual: 'I spent the whole Saturday getting rid of clutter to make space in my bedroom.' } },

  // ── Travel (5) ────────────────────────────────────────────────────────────
  { id: 'tr1', word: 'itinerary', pos: 'noun', level: 'B1', ipa_us: '/aɪˈtɪnəreri/', ipa_uk: '/aɪˈtɪnərəri/', definition_en: 'A planned route or journey, especially with details of places', definition_id: 'Rencana rute atau perjalanan, terutama dengan detail tempat', example_en: 'Our travel itinerary includes five countries.', example_id: 'Itinerary perjalanan kami mencakup lima negara.', category: 'Travel', emoji: '🗺️', contexts: { tech: 'AI travel apps generate personalised itineraries based on your preferences and budget.', business: 'Please share the full business trip itinerary at least 48 hours before departure.', casual: 'We made a loose itinerary for the road trip but left plenty of room for surprises.' } },
  { id: 'tr2', word: 'layover', pos: 'noun', level: 'B1', ipa_us: '/ˈleɪoʊvər/', ipa_uk: '/ˈleɪəʊvə/', definition_en: 'A period of rest in a journey, especially between flights', definition_id: 'Periode istirahat dalam perjalanan, terutama antar penerbangan', example_en: 'We have a 3-hour layover in Singapore.', example_id: 'Kami memiliki layover 3 jam di Singapura.', category: 'Travel', emoji: '✈️', contexts: { tech: 'The flight booking algorithm avoids layovers shorter than 90 minutes to reduce missed connections.', business: 'A six-hour layover in Dubai gave the sales team time for a quick city visit.', casual: 'We used the long layover to explore the airport food hall and try the local cuisine.' } },
  { id: 'tr3', word: 'customs', pos: 'noun', level: 'A2', ipa_us: '/ˈkʌstəmz/', ipa_uk: '/ˈkʌstəmz/', definition_en: 'The official process of checking goods and people entering a country', definition_id: 'Proses resmi pemeriksaan barang dan orang yang masuk ke suatu negara', example_en: 'Please declare all items at customs.', example_id: 'Harap nyatakan semua barang di bea cukai.', category: 'Travel', emoji: '🛃', contexts: { tech: 'New AI scanners at customs can process passengers 40 percent faster than manual checks.', business: 'The import shipment was delayed at customs due to missing documentation.', casual: 'Always declare your snacks at customs or you might get a fine at the border.' } },
  { id: 'tr4', word: 'backpack', pos: 'verb', level: 'A2', ipa_us: '/ˈbækpæk/', ipa_uk: '/ˈbækpæk/', definition_en: 'To travel with only a backpack, especially on a budget', definition_id: 'Bepergian hanya dengan ransel, biasanya dengan anggaran terbatas', example_en: 'She backpacked through Southeast Asia for two months.', example_id: 'Dia backpacking menjelajahi Asia Tenggara selama dua bulan.', category: 'Travel', emoji: '🎒', contexts: { tech: 'Digital nomads often backpack while working remotely with just a laptop and portable WiFi.', business: 'The startup founder backpacked through Asia to research emerging consumer markets firsthand.', casual: 'I want to backpack across Europe next summer and stay in hostels to save money.' } },
  { id: 'tr5', word: 'jet lag', pos: 'phrase', level: 'A2', ipa_us: '/ˈdʒet læɡ/', ipa_uk: '/ˈdʒet læɡ/', definition_en: 'Tiredness and disorientation from crossing multiple time zones', definition_id: 'Kelelahan dan disorientasi akibat melewati beberapa zona waktu', example_en: 'It took me three days to recover from jet lag.', example_id: 'Saya butuh tiga hari untuk pulih dari jet lag.', category: 'Travel', emoji: '😴', contexts: { tech: 'Some health apps use your sleep data to suggest the best schedule to recover from jet lag.', business: 'Experienced executives manage jet lag by adjusting their sleep schedules before the trip.', casual: 'The jet lag hit me hard after the flight from London and I slept for 12 hours straight.' } },

  // ── Academic (5) ─────────────────────────────────────────────────────────
  { id: 'ac1', word: 'hypothesis', pos: 'noun', level: 'B2', ipa_us: '/haɪˈpɒθɪsɪs/', ipa_uk: '/haɪˈpɒθɪsɪs/', definition_en: 'A proposed explanation based on limited evidence', definition_id: 'Penjelasan yang diusulkan berdasarkan bukti terbatas', example_en: 'The scientist tested her hypothesis with experiments.', example_id: 'Ilmuwan itu menguji hipotesisnya dengan eksperimen.', category: 'Academic', emoji: '🔬', contexts: { tech: 'A/B testing lets product teams validate each hypothesis quickly with real user data.', business: 'Our hypothesis was that lower prices would increase volume, and the data confirmed it.', casual: "My hypothesis is that coffee tastes better when you're tired, and I test it every morning." } },
  { id: 'ac2', word: 'thesis', pos: 'noun', level: 'B2', ipa_us: '/ˈθiːsɪs/', ipa_uk: '/ˈθiːsɪs/', definition_en: 'A long essay or dissertation on a particular subject', definition_id: 'Esai atau disertasi panjang tentang subjek tertentu', example_en: 'She spent two years writing her doctoral thesis.', example_id: 'Dia menghabiskan dua tahun menulis tesis doktoralnya.', category: 'Academic', emoji: '📝', contexts: { tech: 'His thesis on distributed consensus algorithms became the foundation for a new blockchain startup.', business: "The consultant's thesis was that digital transformation required culture change, not just new tools.", casual: "My friend's thesis is that pineapple belongs on pizza and she defends it with full conviction." } },
  { id: 'ac3', word: 'citation', pos: 'noun', level: 'B1', ipa_us: '/saɪˈteɪʃən/', ipa_uk: '/saɪˈteɪʃən/', definition_en: 'A reference to a published source within an academic text', definition_id: 'Referensi ke sumber yang diterbitkan dalam teks akademik', example_en: 'Always include proper citations in your research paper.', example_id: 'Selalu sertakan kutipan yang tepat dalam makalah penelitianmu.', category: 'Academic', emoji: '📖', contexts: { tech: 'Tools like Zotero automatically generate citations from web pages and academic databases.', business: 'Citing industry reports in your pitch deck adds credibility to your market claims.', casual: "Mum always wants a citation when I say something surprising, like she's fact-checking me." } },
  { id: 'ac4', word: 'methodology', pos: 'noun', level: 'C1', ipa_us: '/ˌmeθəˈdɒlədʒi/', ipa_uk: '/ˌmeθəˈdɒlədʒi/', definition_en: 'A system of methods used in a particular area of study', definition_id: 'Sistem metode yang digunakan dalam bidang studi tertentu', example_en: 'The research methodology was clearly explained in the paper.', example_id: 'Metodologi penelitian dijelaskan dengan jelas dalam makalah tersebut.', category: 'Academic', emoji: '⚗️', contexts: { tech: 'Scrum is a software development methodology that breaks work into short iterative sprints.', business: 'The consulting firm applied a proven methodology to restructure the supply chain.', casual: 'My methodology for deciding what to eat is to open every app and go with whatever loads first.' } },
  { id: 'ac5', word: 'peer review', pos: 'phrase', level: 'C1', ipa_us: '/ˈpɪr rɪˌvjuː/', ipa_uk: '/ˈpɪə rɪˌvjuː/', definition_en: 'Evaluation of scientific work by experts in the same field', definition_id: 'Evaluasi karya ilmiah oleh para ahli di bidang yang sama', example_en: 'All submissions go through a rigorous peer review process.', example_id: 'Semua kiriman melalui proses peer review yang ketat.', category: 'Academic', emoji: '🧑‍🏫', contexts: { tech: 'GitHub pull requests function as a form of peer review for code quality and correctness.', business: 'Investment proposals go through an internal peer review before presentation to the board.', casual: 'I had my friend give my essay a peer review before I submitted it and she caught many errors.' } },

  // ── Emotions (5) ─────────────────────────────────────────────────────────
  { id: 'em1', word: 'melancholy', pos: 'noun', level: 'B2', ipa_us: '/ˈmelənkɒli/', ipa_uk: '/ˈmelənkɒli/', definition_en: 'A deep, persistent feeling of sadness or depression', definition_id: 'Perasaan sedih atau depresi yang mendalam dan persisten', example_en: 'There was a touch of melancholy in his voice.', example_id: 'Ada sedikit melankolia dalam suaranya.', category: 'Emotions', emoji: '🌧️', contexts: { tech: 'Late-night debugging sessions often bring a certain melancholy when nothing seems to work.', business: 'There was a collective melancholy when the beloved founder announced his retirement.', casual: 'Rainy Sunday afternoons always bring a pleasant melancholy that is perfect for reading.' } },
  { id: 'em2', word: 'exhilarate', pos: 'verb', level: 'B2', ipa_us: '/ɪɡˈzɪləreɪt/', ipa_uk: '/ɪɡˈzɪləreɪt/', definition_en: 'To make someone feel very happy and excited', definition_id: 'Membuat seseorang merasa sangat bahagia dan bersemangat', example_en: 'The mountain view exhilarated the climbers.', example_id: 'Pemandangan gunung membuat para pendaki bergairah.', category: 'Emotions', emoji: '🎉', contexts: { tech: 'Shipping a feature you built from scratch never fails to exhilarate even experienced engineers.', business: 'Closing the biggest deal in company history exhilarated the entire sales team.', casual: 'The roller coaster absolutely exhilarated me even though I was terrified at first.' } },
  { id: 'em3', word: 'apprehensive', pos: 'adjective', level: 'B2', ipa_us: '/ˌæprɪˈhensɪv/', ipa_uk: '/ˌæprɪˈhensɪv/', definition_en: 'Anxious or fearful about a future event', definition_id: 'Cemas atau takut tentang suatu kejadian di masa depan', example_en: 'She was apprehensive about her first job interview.', example_id: 'Dia merasa cemas tentang wawancara kerja pertamanya.', category: 'Emotions', emoji: '😰', contexts: { tech: 'The team was apprehensive before the zero-downtime migration of the live database.', business: 'Investors were apprehensive about the market expansion given the economic uncertainty.', casual: 'I was apprehensive about trying durian for the first time but it was actually delicious.' } },
  { id: 'em4', word: 'nostalgia', pos: 'noun', level: 'B1', ipa_us: '/nɒˈstælɡɪə/', ipa_uk: '/nɒˈstælɡɪə/', definition_en: 'A sentimental longing for the past', definition_id: 'Kerinduan yang sentimental terhadap masa lalu', example_en: 'The old song filled him with nostalgia.', example_id: 'Lagu lama itu membuatnya dipenuhi nostalgia.', category: 'Emotions', emoji: '🕰️', contexts: { tech: 'There is a nostalgia for the early web era when sites were simple and loading times were slow.', business: 'Brands often leverage nostalgia in marketing to create emotional connections with older customers.', casual: 'Eating instant noodles fills me with nostalgia for my university days.' } },
  { id: 'em5', word: 'serene', pos: 'adjective', level: 'B1', ipa_us: '/səˈriːn/', ipa_uk: '/səˈriːn/', definition_en: 'Calm, peaceful, and untroubled', definition_id: 'Tenang, damai, dan tidak terganggu', example_en: 'The lake was serene in the early morning light.', example_id: 'Danau itu tenang dalam cahaya pagi yang awal.', category: 'Emotions', emoji: '🕊️', contexts: { tech: 'A well-designed UI feels serene, allowing users to focus without visual noise or distraction.', business: 'Despite the chaotic launch week, the CEO remained serene and focused on the big picture.', casual: 'Early mornings in the village are absolutely serene before everyone else wakes up.' } },

  // ── Nature (5) ───────────────────────────────────────────────────────────
  { id: 'n1', word: 'canopy', pos: 'noun', level: 'B1', ipa_us: '/ˈkænəpi/', ipa_uk: '/ˈkænəpi/', definition_en: 'The uppermost layer of branches in a forest', definition_id: 'Lapisan paling atas dari cabang-cabang di hutan', example_en: 'Monkeys swung through the forest canopy.', example_id: 'Monyet-monyet berayun melalui kanopi hutan.', category: 'Nature', emoji: '🌳', contexts: { tech: 'Satellite imagery is used to measure deforestation by tracking canopy loss over time.', business: 'The eco-resort marketed its canopy walkways as a premium nature experience for guests.', casual: 'We sat beneath the canopy of old trees in the park to escape the summer heat.' } },
  { id: 'n2', word: 'erosion', pos: 'noun', level: 'B2', ipa_us: '/ɪˈroʊʒən/', ipa_uk: '/ɪˈrəʊʒən/', definition_en: 'The gradual wearing away of land by water, wind, or ice', definition_id: 'Pengikisan tanah secara bertahap oleh air, angin, atau es', example_en: 'Coastal erosion is threatening the cliffs.', example_id: 'Erosi pesisir mengancam tebing-tebing tersebut.', category: 'Nature', emoji: '🏔️', contexts: { tech: 'Drones are deployed to monitor soil erosion patterns in real time across farmland.', business: 'Brand erosion occurred when the company failed to respond to the PR crisis quickly enough.', casual: 'Years of erosion have shaped these cliffs into the most beautiful natural sculptures.' } },
  { id: 'n3', word: 'hibernate', pos: 'verb', level: 'B1', ipa_us: '/ˈhaɪbərneɪt/', ipa_uk: '/ˈhaɪbəneɪt/', definition_en: 'To spend winter in a dormant state', definition_id: 'Menghabiskan musim dingin dalam keadaan dorman', example_en: 'Bears hibernate during the cold winter months.', example_id: 'Beruang berhibernasi selama bulan-bulan musim dingin yang dingin.', category: 'Nature', emoji: '🐻', contexts: { tech: 'The laptop hibernates after 30 minutes of inactivity to preserve battery life.', business: 'The startup decided to hibernate the project and revisit it when funding improved.', casual: 'Honestly, all I want to do in winter is hibernate under a warm blanket like a bear.' } },
  { id: 'n4', word: 'precipitation', pos: 'noun', level: 'B2', ipa_us: '/prɪˌsɪpɪˈteɪʃən/', ipa_uk: '/prɪˌsɪpɪˈteɪʃən/', definition_en: 'Water that falls from the sky as rain, snow, or hail', definition_id: 'Air yang jatuh dari langit sebagai hujan, salju, atau hujan es', example_en: 'High precipitation levels can cause flooding.', example_id: 'Tingkat curah hujan yang tinggi dapat menyebabkan banjir.', category: 'Nature', emoji: '🌧️', contexts: { tech: 'Weather APIs provide hourly precipitation forecasts used by farming management systems.', business: 'The outdoor event was cancelled due to extreme precipitation levels forecast for the weekend.', casual: 'The weather app warned of heavy precipitation so I carried my umbrella all day just in case.' } },
  { id: 'n5', word: 'sanctuary', pos: 'noun', level: 'B1', ipa_us: '/ˈsæŋktʃueri/', ipa_uk: '/ˈsæŋktʃuəri/', definition_en: 'A protected area for wildlife or a place of refuge', definition_id: 'Area yang dilindungi untuk satwa liar atau tempat perlindungan', example_en: 'The national park serves as a wildlife sanctuary.', example_id: 'Taman nasional berfungsi sebagai suaka satwa liar.', category: 'Nature', emoji: '🦁', contexts: { tech: 'The team created a distraction-free coding sanctuary with tools blocked and notifications silenced.', business: 'The private island resort was marketed as a luxury sanctuary away from the corporate world.', casual: 'My bedroom is my personal sanctuary where nobody is allowed to disturb me on weekends.' } },

  // ── Health (5) ───────────────────────────────────────────────────────────
  { id: 'h1', word: 'resilience', pos: 'noun', level: 'B2', ipa_us: '/rɪˈzɪlɪəns/', ipa_uk: '/rɪˈzɪlɪəns/', definition_en: 'The capacity to recover quickly from difficulties', definition_id: 'Kemampuan untuk pulih dengan cepat dari kesulitan', example_en: 'Mental resilience is key to handling stress.', example_id: 'Ketahanan mental adalah kunci untuk menangani stres.', category: 'Health', emoji: '💪', contexts: { tech: 'Distributed systems are built for resilience so that one node failure does not crash everything.', business: 'The company demonstrated remarkable resilience by bouncing back after the data breach.', casual: 'You need real resilience to run a marathon; the mental part is just as hard as the physical.' } },
  { id: 'h2', word: 'nutrition', pos: 'noun', level: 'A2', ipa_us: '/njuːˈtrɪʃən/', ipa_uk: '/njuːˈtrɪʃən/', definition_en: 'The process of providing the food necessary for growth and health', definition_id: 'Proses penyediaan makanan yang diperlukan untuk pertumbuhan dan kesehatan', example_en: 'Good nutrition is essential during childhood.', example_id: 'Nutrisi yang baik sangat penting selama masa kanak-kanak.', category: 'Health', emoji: '🥗', contexts: { tech: 'The fitness app tracks nutrition by scanning barcodes and logging macros automatically.', business: 'The hospital chain launched a corporate nutrition programme to reduce employee sick days.', casual: 'I started paying more attention to nutrition after feeling tired all the time at work.' } },
  { id: 'h3', word: 'sedentary', pos: 'adjective', level: 'B2', ipa_us: '/ˈsedənteri/', ipa_uk: '/ˈsedəntri/', definition_en: 'Spending too much time sitting and not exercising enough', definition_id: 'Menghabiskan terlalu banyak waktu duduk dan tidak cukup berolahraga', example_en: 'A sedentary lifestyle increases the risk of heart disease.', example_id: 'Gaya hidup sedentari meningkatkan risiko penyakit jantung.', category: 'Health', emoji: '🛋️', contexts: { tech: 'Smartwatches send reminders to stand up and move to counter sedentary desk work habits.', business: 'The company introduced standing desks after a study revealed dangerously sedentary habits.', casual: 'I realised my weekend was completely sedentary when I counted just 500 steps on my watch.' } },
  { id: 'h4', word: 'immune system', pos: 'phrase', level: 'B1', ipa_us: '/ɪˈmjuːn ˈsɪstəm/', ipa_uk: '/ɪˈmjuːn ˈsɪstəm/', definition_en: "The body's defence mechanism against infection and disease", definition_id: 'Mekanisme pertahanan tubuh terhadap infeksi dan penyakit', example_en: 'Sleep helps strengthen your immune system.', example_id: 'Tidur membantu memperkuat sistem kekebalan tubuh Anda.', category: 'Health', emoji: '🛡️', contexts: { tech: 'Bioinformatics tools analyse immune system responses at the molecular level for vaccine design.', business: 'The wellness programme was designed to boost employee immune systems and reduce absences.', casual: 'I eat lots of citrus in winter to keep my immune system strong during flu season.' } },
  { id: 'h5', word: 'cardiovascular', pos: 'adjective', level: 'B2', ipa_us: '/ˌkɑːrdioʊˈvæskjʊlər/', ipa_uk: '/ˌkɑːdiəʊˈvæskjʊlə/', definition_en: 'Relating to the heart and blood vessels', definition_id: 'Berkaitan dengan jantung dan pembuluh darah', example_en: 'Regular cardio exercise improves cardiovascular health.', example_id: 'Olahraga kardio rutin meningkatkan kesehatan kardiovaskular.', category: 'Health', emoji: '❤️', contexts: { tech: 'Wearable sensors now give real-time cardiovascular data to both athletes and cardiologists.', business: 'The insurance company offered discounts to employees who demonstrated strong cardiovascular fitness.', casual: 'My doctor said I need more cardiovascular exercise, so I started cycling to work every day.' } },

  // ── Culture (5) ──────────────────────────────────────────────────────────
  { id: 'cu1', word: 'indigenous', pos: 'adjective', level: 'B2', ipa_us: '/ɪnˈdɪdʒɪnəs/', ipa_uk: '/ɪnˈdɪdʒɪnəs/', definition_en: 'Originating or occurring naturally in a particular place', definition_id: 'Berasal atau terjadi secara alami di tempat tertentu', example_en: 'We should preserve indigenous languages and traditions.', example_id: 'Kita harus melestarikan bahasa dan tradisi adat.', category: 'Culture', emoji: '🏛️', contexts: { tech: 'Tech companies are building tools to digitally preserve indigenous languages before they disappear.', business: 'The corporation partnered with indigenous communities to develop ethical tourism products.', casual: 'I learned about indigenous art forms during our visit to the national museum last weekend.' } },
  { id: 'cu2', word: 'heritage', pos: 'noun', level: 'B1', ipa_us: '/ˈherɪtɪdʒ/', ipa_uk: '/ˈherɪtɪdʒ/', definition_en: 'Values, traditions, and culture passed from generation to generation', definition_id: 'Nilai, tradisi, dan budaya yang diwariskan dari generasi ke generasi', example_en: 'The city has a rich cultural heritage.', example_id: 'Kota ini memiliki warisan budaya yang kaya.', category: 'Culture', emoji: '🏺', contexts: { tech: 'Virtual reality tours let people explore heritage sites that are too fragile for physical visitors.', business: 'The brand leveraged its century-old heritage in its premium marketing campaigns globally.', casual: 'My grandmother always says our food heritage connects us to ancestors we never met.' } },
  { id: 'cu3', word: 'folklore', pos: 'noun', level: 'B1', ipa_us: '/ˈfoʊklɔːr/', ipa_uk: '/ˈfəʊklɔː/', definition_en: 'Traditional stories, customs, and beliefs of a community', definition_id: 'Cerita, adat, dan kepercayaan tradisional suatu komunitas', example_en: 'Indonesian folklore is rich with mythical creatures.', example_id: 'Cerita rakyat Indonesia kaya dengan makhluk mitos.', category: 'Culture', emoji: '📜', contexts: { tech: 'Researchers use NLP tools to digitise and analyse patterns across centuries of folklore texts.', business: 'The game studio built its entire IP around Southeast Asian folklore to stand out in the market.', casual: 'My grandmother would tell us folklore stories every night before bed when we were kids.' } },
  { id: 'cu4', word: 'assimilate', pos: 'verb', level: 'C1', ipa_us: '/əˈsɪmɪleɪt/', ipa_uk: '/əˈsɪmɪleɪt/', definition_en: 'To absorb and integrate into a wider culture', definition_id: 'Menyerap dan mengintegrasikan ke dalam budaya yang lebih luas', example_en: 'Immigrants often assimilate while preserving their original culture.', example_id: 'Para imigran sering berasimilasi sambil melestarikan budaya asli mereka.', category: 'Culture', emoji: '🌍', contexts: { tech: 'New engineers need time to assimilate the team coding conventions and unwritten rules.', business: 'Post-merger integration efforts focused on helping employees assimilate to the new company culture.', casual: 'Moving to a new city helped me assimilate different food cultures into my everyday cooking.' } },
  { id: 'cu5', word: 'etiquette', pos: 'noun', level: 'B1', ipa_us: '/ˈetɪkɪt/', ipa_uk: '/ˈetɪkɪt/', definition_en: 'The customary code of polite behaviour in a society', definition_id: 'Kode perilaku sopan yang lazim dalam masyarakat', example_en: 'Learning local etiquette is important when travelling.', example_id: 'Mempelajari etika lokal penting saat bepergian.', category: 'Culture', emoji: '🤵', contexts: { tech: 'Slack etiquette guidelines were posted to help remote teams communicate without misunderstandings.', business: 'Business card etiquette in Japan requires accepting the card with both hands and reading it carefully.', casual: 'There is a whole etiquette around queueing in the UK that visitors must learn quickly.' } },

  // ── Food (5) ─────────────────────────────────────────────────────────────
  { id: 'f1', word: 'cuisine', pos: 'noun', level: 'A2', ipa_us: '/kwɪˈziːn/', ipa_uk: '/kwɪˈziːn/', definition_en: 'A style or method of cooking characteristic of a country', definition_id: 'Gaya atau metode memasak yang khas dari suatu negara', example_en: 'Thai cuisine is known for its balance of flavours.', example_id: 'Masakan Thailand terkenal dengan keseimbangan rasanya.', category: 'Food', emoji: '🍜', contexts: { tech: 'Food delivery apps now categorise cuisine by flavour profile and dietary preference.', business: 'The hotel chain invested in authentic local cuisine to differentiate its restaurant offering.', casual: 'My favourite cuisine is Japanese because every dish is prepared with such amazing care.' } },
  { id: 'f2', word: 'ferment', pos: 'verb', level: 'B2', ipa_us: '/fərˈment/', ipa_uk: '/fəˈment/', definition_en: 'To undergo chemical changes through bacteria or yeast', definition_id: 'Mengalami perubahan kimia melalui bakteri atau ragi', example_en: 'Yogurt is made by fermenting milk.', example_id: 'Yogurt dibuat dengan memfermentasi susu.', category: 'Food', emoji: '🫙', contexts: { tech: 'Bioreactors monitor temperature and pH levels as microbes ferment plant-based proteins at scale.', business: 'The craft beverage startup built its brand around locally sourced ingredients they ferment in-house.', casual: 'I started to ferment my own kimchi at home after watching a video about Korean cooking.' } },
  { id: 'f3', word: 'savoury', pos: 'adjective', level: 'A2', ipa_us: '/ˈseɪvəri/', ipa_uk: '/ˈseɪvəri/', definition_en: 'Having a pleasant salty or spicy taste, not sweet', definition_id: 'Memiliki rasa asin atau pedas yang menyenangkan, bukan manis', example_en: 'I prefer savoury snacks over sweet ones.', example_id: 'Saya lebih suka camilan gurih daripada yang manis.', category: 'Food', emoji: '🧂', contexts: { tech: 'Food tech companies are engineering plant-based proteins with a savoury umami depth that satisfies.', business: 'Consumer research showed savoury flavours outperformed sweet in the lunchtime snack category.', casual: 'Give me savoury food any day over sweet I am completely a crisps and cheese person.' } },
  { id: 'f4', word: 'garnish', pos: 'verb', level: 'B1', ipa_us: '/ˈɡɑːrnɪʃ/', ipa_uk: '/ˈɡɑːnɪʃ/', definition_en: 'To decorate food with a small amount of another food', definition_id: 'Mendekorasi makanan dengan sedikit makanan lain', example_en: 'Garnish the soup with fresh parsley before serving.', example_id: 'Hiasi sup dengan peterseli segar sebelum disajikan.', category: 'Food', emoji: '🌿', contexts: { tech: 'Restaurant apps let chefs photograph each dish before they garnish to ensure visual consistency.', business: "A simple garnish can elevate a dish's perceived value and justify a premium price point.", casual: 'I always garnish my avocado toast with chilli flakes and a squeeze of lime for extra flavour.' } },
  { id: 'f5', word: 'simmer', pos: 'verb', level: 'A2', ipa_us: '/ˈsɪmər/', ipa_uk: '/ˈsɪmə/', definition_en: 'To cook slowly at just below boiling point', definition_id: 'Memasak perlahan di bawah titik didih', example_en: 'Let the sauce simmer for 20 minutes.', example_id: 'Biarkan saus mendidih perlahan selama 20 menit.', category: 'Food', emoji: '🍲', contexts: { tech: 'Smart cookers monitor temperature to keep soup at a perfect simmer without overcooking.', business: 'Tensions in the team had been simmering for weeks before the manager finally addressed them.', casual: 'There is nothing better than letting a good broth simmer all afternoon to fill the house with warmth.' } },
];

export const vocabularyCategories = [
  'Business', 'Tech/AI', 'Daily Life', 'Travel', 'Academic',
  'Emotions', 'Nature', 'Health', 'Culture', 'Food',
];